services:
  nessie-db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5433:5432" # Use a different host port to avoid conflict if another postgres is running
    environment:
      - POSTGRES_USER=nessie
      - POSTGRES_PASSWORD=nessie
      - POSTGRES_DB=nessie_catalog
    volumes:
      - nessie_db_data:/var/lib/postgresql/data

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - NESSIE_VERSION_STORE_TYPE=JDBC
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://nessie-db:5432/nessie_catalog
      - QUARKUS_DATASOURCE_USERNAME=nessie
      - QUARKUS_DATASOURCE_PASSWORD=nessie
    depends_on:
      - nessie-db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  trino-coordinator:
    image: trinodb/trino:435
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino/config.properties:/etc/trino/config.properties
      - ./trino/jvm.config:/etc/trino/jvm.config
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties
    depends_on:
      - nessie
      - minio

volumes:
  nessie_db_data:
  minio_data:
