base_dbt:
  outputs:

    dev:
      type: trino
      method: none
      user: dbt_user
      host: localhost
      port: 8080
      database: iceberg
      schema: dbt_models
      threads: 1

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [prod_user]
      password: [prod_password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [prod_schema]
      threads: [1 or more]

  target: dev
